FROM node:lts-alpine3.16

# # Dev tools and open3d-compatible python version
# RUN apt-get -y update \
#     && apt-get install -y software-properties-common \
#     && DEBIAN_FRONTEND=noninteractive apt-get install -y \
#     nodejs npm \
#     && rm -rf /var/lib/apt/lists/* \
#     && apt-get clean

# Install npm dependencies
ENV SOURCE_DIR=/tactil
WORKDIR ${SOURCE_DIR}/ui
COPY ui/package-lock.json ui/package.json ./
RUN npm ci --omit=dev && npm cache clean --force

# Copy source files
COPY . ${SOURCE_DIR}

WORKDIR ${SOURCE_DIR}/ui
CMD npm start
