FROM node:lts-alpine3.16

# Install npm dependencies
ENV SOURCE_DIR=/tactil/ui
WORKDIR ${SOURCE_DIR}
COPY ui/package-lock.json ui/package.json ./
RUN npm ci --omit=dev && npm cache clean --force

# Copy source files
COPY ./ui ${SOURCE_DIR}

WORKDIR ${SOURCE_DIR}
CMD npm start
